apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    pv: grafana-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - xxx-okd-prd-cephfs1:6789
      - xxx-okd-prd-cephfs2:6789
      - xxx-okd-prd-cephfs3:6789
    user: admin
    path: /openshift-dev/cephfs/grafana/
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Delete
