apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: cephfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: grafana-pv
  selector:
    matchLabels:
      pv: grafana-pv
  storageClassName: ''
