apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    run: prometheus-server
  name: prometheus-server
  namespace: cephfs
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    run: prometheus-server
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        run: prometheus-server
    spec:
      containers:
      - image: prom/prometheus:v2.15.2
        imagePullPolicy: IfNotPresent
        name: prometheus-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/secret/etcd
          name: kube-etcd-client-certs
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /etc/prometheus/rules
          name: prometheus-rules
        - mountPath: /prometheus
          name: prometheus-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-config
        name: prometheus-config
      - configMap:
          defaultMode: 420
          name: prometheus-rules
        name: prometheus-rules
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-pvc
      - name: kube-etcd-client-certs
        secret:
          defaultMode: 420
          secretName: kube-etcd-client-certs
      test: false
  triggers:
  - type: ConfigChange
