global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']
  #etcd
  - job_name: etcd-server
    scheme: https
    tls_config:
    # CA certificate to validate API server certificate with.
    [ ca_file: /etc/prometheus/secret/etcd/etcd-client-ca.crt ]
    
    # Certificate and key files for client cert authentication to the server.
    [ cert_file: /etc/prometheus/secret/etcd/etcd-client.crt ]
    [ key_file: /etc/prometheus/secret/etcd/etcd-client.key ]
   #   insecure_skip_verify: true
    static_configs:
    - targets: ['10.122.20.210:2379','10.122.20.212:2379','10.122.20.213:2379'] 
  #ceph
  - job_name: 'ceph-exporter'

    static_configs:
    - targets: ['10.122.20.214:9128']
      labels:
        alias: ceph-exporter
