apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metrics-cassandra-2
  namespace: openshift-infra
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: cassandra-storage-2
