apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-storage-1
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - xxx-okd-prd-cephfs1:6789
      - xxx-okd-prd-cephfs2:6789
      - xxx-okd-prd-cephfs3:6789
    user: admin
    path: /openshift-dev/openshift-infra/cassandra-storage-1/
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Delete
