apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-new
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: registry-new-volume
  selector:
    matchLabels:
      pv: registry-new
  storageClassName: ''
