apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-new-volume
  labels:
    pv: registry-new
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - xxx-okd-prd-cephfs1:6789
      - xxx-okd-prd-cephfs2:6789
      - xxx-okd-prd-cephfs3:6789
    user: admin
    path: /openshift-dev/default/registry-new/
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Delete
