apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  volumeName: registry-volume
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  phase: Bound
