kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cephfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ceph.com/cephfs
#allowVolumeExpansion: true
parameters:
    monitors: 10.122.20.214:6789,10.122.20.215:6789,10.122.20.216:6789
    adminId: admin
    adminSecretName: ceph-secret
    adminSecretNamespace: "kube-system"
#    claimRoot: /volumes/kubernetes/
    claimRoot: /volumes/openshift-dev/
