apiVersion: v1
kind: PersistentVolume
metadata:
  name: vms-nginx-conf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - szpbs-okd-prd-cephfs1:6789
      - szpbs-okd-prd-cephfs2:6789
      - szpbs-okd-prd-cephfs3:6789
    user: admin
    path: /cephfs/openshift-dev/vms-dev/vms-nginx/conf
    secretRef:
      name: ceph-secret
    readOnly: false
  persistentVolumeReclaimPolicy: Delete
