apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-convert-chinese
  namespace: openshift-web-console
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: web-convert-chinese
