apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: rabbitmq
    name: mqadmin
  spec:
    ports:
    - name: http
      port: 15672
      protocol: TCP
      targetPort: 15672
    selector:
      run: rabbitmq
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      run: rabbitmq
    name: rabbitmq
  spec:
    ports:
    - name: http
      port: 5672
      protocol: TCP
      targetPort: 5672
    selector:
      run: rabbitmq
